language: python
dist: xenial

python:
  - "3.6"

env:
  - DB=mysql
  - DB=postgres
  - DB=sqlite

install:
  - pip install -q tox-travis

before_script:
  - mysql -e 'create database sendgrid;'
  - psql -c 'create database sendgrid;' -U postgres

script:
    - tox
