language: python

python:
  - "2.7"

env:
  - TOXENV=py27-1.4.X
  - TOXENV=py27-1.5.X
  - TOXENV=py27-1.6.X
  - TOXENV=py27-1.7.X
  - TOXENV=flake8

install:
  - pip install tox

script:
    - tox

branches:
  only:
    - master

matrix:
  allow_failures:
    - env: TOXENV=py27-1.7.X
